#!/bin/bash
# Switch the target root to use systemd-boot, using
# the content from SRC
set -xeuo pipefail

src=$1
shift

# Uninstall bootupd
rpm -e bootupd
rm -vrf /usr/lib/bootupd/updates

# Install systemd-boot and remove bootupd;
# We downloaded this in an earlier phase
sdboot=$(ls /usr/lib/systemd/boot/efi/systemd-boot*.efi)
sdboot_bn=$(basename ${sdboot})
rpm -Uvh ${src}/*.rpm
# And override with our signed binary
install -m 0644 ${src}/${sdboot_bn} /${sdboot}
