name: "Commit Verification"

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  verify-commits:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'control/skip-ci') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install just
        run: sudo apt update && sudo apt install just
          
      - name: Run git commit verification
        run: just git-check ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
